import StubPage from "@/components/StubPage";

export const BrandBrain = () => <StubPage title="Brand Brain" description="Define your ICP, voice, claims, and proof. Your brand memory powers everything." />;
export const InfluencerStudio = () => <StubPage title="Influencer Studio" description="Create and manage your AI-powered influencers." />;
export const VideoStudio = () => <StubPage title="Video Studio" description="Script-to-video creation with scene builder and lip sync." />;
export const VideoStudioPro = () => <StubPage title="Video Studio Pro" description="Advanced video creation with professional tools." />;
export const CampaignFactory = () => <StubPage title="Campaign Factory" description="Create unified campaign objects with auto-generated assets." />;
export const Campaigns = () => <StubPage title="Campaigns" description="View and manage all your campaigns." />;
export const CampaignDetail = () => <StubPage title="Campaign Detail" description="Campaign details and performance." />;
export const Schedule = () => <StubPage title="Scheduler" description="Schedule and auto-publish across all channels." />;
export const Analytics = () => <StubPage title="Analytics" description="Track campaign performance and insights." />;
export const AnalyticsHub = () => <StubPage title="Analytics Hub" description="Unified analytics dashboard with A/B test results." />;
export const ABTesting = () => <StubPage title="A/B Testing" description="Run experiments and compare campaign variations." />;
export const Templates = () => <StubPage title="Templates" description="Campaign and content templates." />;
export const TemplateMarketplace = () => <StubPage title="Template Marketplace" description="Browse and install community templates." />;
export const Leads = () => <StubPage title="Leads" description="Track and manage captured leads." />;
export const SocialConnections = () => <StubPage title="Social Connections" description="Connect your social media accounts for publishing." />;
export const VideoScripts = () => <StubPage title="Video Scripts" description="AI-generated video scripts and storyboards." />;
export const Brands = () => <StubPage title="Brands" description="Manage multiple brands for your agency." />;
export const WhiteLabel = () => <StubPage title="White Label" description="Customize the platform with your agency branding." />;
export const Team = () => <StubPage title="Team" description="Manage team members and permissions." />;
export const Notifications = () => <StubPage title="Notifications" description="View your notifications and alerts." />;
export const AccountSettings = () => <StubPage title="Account Settings" description="Manage your account, billing, and preferences." />;
export const CreateInfluencer = () => <StubPage title="Create Influencer" description="Create a new AI influencer." />;
export const CreateInfluencerPro = () => <StubPage title="Create Influencer Pro" description="Advanced influencer creation with character controls." />;
export const GenerationWorkspace = () => <StubPage title="Generation Workspace" description="Your influencer image generation workspace." />;
export const Chat = () => <StubPage title="Chat" description="Chat with your AI influencer." />;
export const Discover = () => <StubPage title="Discover" description="Explore AI influencer profiles and templates." />;
export const InfluencerDetail = () => <StubPage title="Influencer Detail" description="View and manage influencer profile." />;
export const AAOGlossary = () => <StubPage title="AAO Glossary" description="Learn about AI-Amplified Operators terminology." />;
export const AAOStudioPage = () => <StubPage title="AAO Studio" description="Create and configure your AI-Amplified Operators." />;
export const AIProvidersPage = () => <StubPage title="AI Providers" description="Configure AI model providers and API keys." />;
export const UsageAnalyticsPage = () => <StubPage title="Usage Analytics" description="Track your platform usage and credits." />;
export const AssetLibrary = () => <StubPage title="Asset Library" description="Manage your generated images, videos, and assets." />;
export const StoryStudio = () => <StubPage title="Story Studio" description="Create multi-scene stories and narratives." />;
export const BulkCreate = () => <StubPage title="Bulk Create" description="Generate content at scale." />;

// Admin pages
export const AdminOverview = () => <StubPage title="Admin Overview" description="System administration dashboard." />;
export const AdminTenants = () => <StubPage title="Admin Tenants" description="Manage platform tenants." />;
export const AdminTenantDetail = () => <StubPage title="Tenant Detail" description="Tenant details and configuration." />;
export const AdminBilling = () => <StubPage title="Admin Billing" description="Manage billing and subscriptions." />;
export const AdminFeatureFlags = () => <StubPage title="Feature Flags" description="Control feature availability." />;
export const AdminAuditLog = () => <StubPage title="Audit Log" description="View system audit trail." />;
export const AdminIntegrations = () => <StubPage title="Admin Integrations" description="Manage platform integrations." />;
export const AdminSystemHealth = () => <StubPage title="System Health" description="Monitor system status." />;
export const AdminModeration = () => <StubPage title="Moderation" description="Content moderation queue." />;
export const AdminCompliance = () => <StubPage title="Compliance" description="Compliance management." />;
export const AdminGdprRequests = () => <StubPage title="GDPR Requests" description="Manage GDPR data requests." />;
export const AdminLeads = () => <StubPage title="Admin Leads" description="Platform-wide lead management." />;
